#!/bin/bash

# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1}'

# Begin the endless array.
echo '['

# We send an empty first array of blocks to make the loop simpler:
echo '[],'

# Now send blocks with information forever:
conky -c ~/.i3/conkyrc
#conky -c ~/.i3/conkyrc | dzen2 -W 960 -h 11 -ta 1 -p -y '1000' -dock
