ZSH_HIGHLIGHT_STYLES[bracket-error]=fg=red,bold,underline
ZSH_HIGHLIGHT_STYLES[bracket-level-1]=fg=82,bold
ZSH_HIGHLIGHT_STYLES[bracket-level-2]=fg=51,bold
ZSH_HIGHLIGHT_STYLES[bracket-level-3]=fg=201,bold
ZSH_HIGHLIGHT_STYLES[bracket-level-4]=fg=231,bold
ZSH_HIGHLIGHT_STYLES[bracket-level-5]=fg=226,bold
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]=standout


ZSH_HIGHLIGHT_STYLES[default]=none
ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=red,bold
ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=yellow
ZSH_HIGHLIGHT_STYLES[alias]=fg=green,bold
ZSH_HIGHLIGHT_STYLES[builtin]=fg=green
ZSH_HIGHLIGHT_STYLES[function]=fg=green,bold
ZSH_HIGHLIGHT_STYLES[command]=fg=green
ZSH_HIGHLIGHT_STYLES[precommand]=fg=green,underline
ZSH_HIGHLIGHT_STYLES[commandseparator]=fg=231,bold
ZSH_HIGHLIGHT_STYLES[hashed-command]=fg=green
ZSH_HIGHLIGHT_STYLES[path]=fg=220
ZSH_HIGHLIGHT_STYLES[path_prefix]=fg=220
ZSH_HIGHLIGHT_STYLES[path_approx]=fg=203
ZSH_HIGHLIGHT_STYLES[globbing]=fg=164
ZSH_HIGHLIGHT_STYLES[history-expansion]=fg=blue
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=fg=45
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]=fg=207
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]=fg=84
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=yellow
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=yellow
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]=fg=cyan
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]=fg=cyan
ZSH_HIGHLIGHT_STYLES[assign]=none
