#!/bin/sh

# /usr/share/sxiv/exec/key-handler
readonly KEY="$1";
readonly TAGFILE="$HOME/.config/sxiv/tags"
readonly TMPFILE="/tmp/sxiv.$$"

case "$1" in
"C-d")
        while read file; do mv "$file" ~/.trash; done ;;
"C-r")
        while read file; do convert -rotate 90 "$file" "$file"; done ;;
esac
